# Generated by Django 6.0.5 on 2026-05-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pfe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('salle', models.CharField(max_length=50)),
                ('duree', models.PositiveIntegerField(help_text='durée en minutes')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REPORTEE', 'Reportée')], default='PLANIFIEE', max_length=10)),
                ('note_finale', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membres_jury', models.ManyToManyField(blank=True, limit_choices_to={'role': 'jury'}, related_name='jurys', to=settings.AUTH_USER_MODEL)),
                ('pfe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='pfe.pfe')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('type', models.CharField(choices=[('jury', 'Jury'), ('encadrant', 'Encadrant'), ('finale', 'Finale')], max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='soutenances.soutenance')),
            ],
            options={
                'unique_together': {('soutenance', 'evaluateur', 'type')},
            },
        ),
    ]
