# Generated by Django 6.0.5 on 2026-06-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_anneeacademique_livrable_hors_delai_pfe_mention_and_more'),
        ('soutenances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances', to='pfe.anneeacademique'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_AUTORISATION', "En attente d'autorisation"), ('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REPORTEE', 'Reportée')], default='PLANIFIEE', max_length=30),
        ),
    ]
