# Generated by Django 6.0.5 on 2026-05-23 12:23

import apps.pfe.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sujets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('filiere', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ARCHIVE', 'Archivé')], default='EN_COURS', max_length=10)),
                ('score_plagiat', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadrant_acad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_acad', to=settings.AUTH_USER_MODEL)),
                ('encadrant_entr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_entr', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfe', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfe', to='sujets.sujet')),
            ],
            options={
                'verbose_name': 'PFE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rapport', 'Rapport'), ('code', 'Code source'), ('presentation', 'Présentation')], max_length=20)),
                ('fichier', models.FileField(upload_to=apps.pfe.models.livrable_upload_path)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=15)),
                ('remarques', models.TextField(blank=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('pfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='pfe.pfe')),
            ],
            options={
                'verbose_name': 'Livrable',
                'ordering': ['-date_depot'],
            },
        ),
    ]
