# Generated by Django 6.0.5 on 2026-06-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-libelle'],
            },
        ),
        migrations.AddField(
            model_name='livrable',
            name='hors_delai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pfe',
            name='mention',
            field=models.CharField(blank=True, choices=[('tres_bien', 'Très bien'), ('bien', 'Bien'), ('assez_bien', 'Assez bien'), ('passable', 'Passable'), ('ajourne', 'Ajourné')], max_length=20),
        ),
        migrations.AddField(
            model_name='pfe',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_set', to='pfe.anneeacademique'),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_livrable', models.CharField(choices=[('rapport', 'Rapport'), ('code', 'Code source'), ('presentation', 'Présentation')], max_length=20)),
                ('date_limite', models.DateTimeField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='pfe.anneeacademique')),
            ],
            options={
                'verbose_name': 'Deadline',
                'ordering': ['date_limite'],
                'unique_together': {('annee_academique', 'type_livrable')},
            },
        ),
    ]
