# Generated by Django 6.0.5 on 2026-06-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_anneeacademique_livrable_hors_delai_pfe_mention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE_ENCADRANT', 'En attente signature encadrant'), ('EN_ATTENTE_COORDINATEUR', 'En attente signature coordinateur'), ('SIGNEE', 'Signée')], default='EN_ATTENTE_ENCADRANT', max_length=30)),
                ('signe_encadrant', models.BooleanField(default=False)),
                ('signe_coordinateur', models.BooleanField(default=False)),
                ('chemin_pdf', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pfe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_inscription', to='pfe.pfe')),
            ],
            options={
                'verbose_name': "Fiche d'inscription PFE",
            },
        ),
    ]
