# Generated by Django 6.0.5 on 2026-06-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0003_fiche_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='date_limite_soutenance',
            field=models.DateField(blank=True, help_text='Dernière date à laquelle une soutenance peut être planifiée dans cette année.', null=True),
        ),
    ]
