# Generated by Django 6.0.5 on 2026-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('sujet_valide', 'Sujet validé'), ('sujet_refuse', 'Sujet refusé'), ('encadrant_affecte', 'Encadrant affecté'), ('livrable_depose', 'Livrable déposé'), ('livrable_valide', 'Livrable validé'), ('livrable_refuse', 'Livrable refusé'), ('soutenance_planifiee', 'Soutenance planifiée'), ('note_publiee', 'Note publiée'), ('deadline', 'Deadline livrable')], max_length=30),
        ),
    ]
