# Generated by Django 6.0.5 on 2026-06-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_etudiants',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
