# Generated by Django 6.0.5 on 2026-05-23 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('origine', models.CharField(choices=[('academique', 'Académique'), ('entreprise', 'Entreprise')], max_length=20)),
                ('statut', models.CharField(choices=[('PROPOSE', 'Proposé'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('AFFECTE', 'Affecté')], default='PROPOSE', max_length=10)),
                ('filiere', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_encadres', to=settings.AUTH_USER_MODEL)),
                ('propose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_proposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sujet',
                'ordering': ['-created_at'],
            },
        ),
    ]
