# Generated by Django 6.0.5 on 2026-05-23 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='etudiant_cible',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'etudiant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_cibles', to=settings.AUTH_USER_MODEL),
        ),
    ]
