# Generated by Django 6.0.5 on 2026-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujets', '0002_sujet_etudiant_cible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='confidentiel',
            field=models.BooleanField(default=False),
        ),
    ]
