# Generated by Django 6.0.5 on 2026-06-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_anneeacademique_livrable_hors_delai_pfe_mention_and_more'),
        ('sujets', '0003_sujet_confidentiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets', to='pfe.anneeacademique'),
        ),
    ]
